# Generated by Django 5.0.3 on 2024-03-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_booking_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(default=153293),
            preserve_default=False,
        ),
    ]
