# Generated by Django 5.0.3 on 2024-03-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
