# Generated by Django 5.0.3 on 2024-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_remove_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=233, max_digits=10),
            preserve_default=False,
        ),
    ]
