# Generated by Django 5.0.3 on 2024-03-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_booking_phone_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
